export const easyDefinitions = [
  {
    _id: "123account",
    word: "account",
    definition:
      "an arrangement with a bank to keep your money there and allow you to take it out when you need to.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123air",
    word: "air",
    definition: "the mixture of gases that surrounds the Earth and that we breathe.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123amount",
    word: "amount",
    definition: "a collection or mass, especially of something that cannot be counted.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123animal",
    word: "animal",
    definition: "something that lives and moves, but is not a human, bird, insect or fish.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123answer",
    word: "answer",
    definition: "the receipt and response to a letter, question or phone call.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123approval",
    word: "approval",
    definition: "the feeling of having a positive opinion of someone or something.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123art",
    word: "art",
    definition:
      "the activity of making objects, drawings, music, paintings, sculptures etc that are beautiful or that express feelings.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123attack",
    word: "attack",
    definition:
      "to try to hurt or defeat (mainly referred to physical violence but can also be used to describe verbal or emotional outbursts).",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123attention",
    word: "attention",
    definition: "notice, thought or interest.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123back",
    word: "back",
    definition:
      "(adverb) in return, into, towards a previous place or condition, or an earlier time; (noun) the part of your body that is opposite to the front, from your shoulder to your bottom.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123base",
    word: "base",
    definition: "the bottom part of an object, on which it rests, or the lowest part of something.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123belief",
    word: "belief",
    definition:
      "the feeling of being certain that something exists or is true, something that you believe.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123birth",
    word: "birth",
    definition: "the time when a young baby, or young animal comes out of its mother’s body.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123blood",
    word: "blood",
    definition: "the red liquid that is sent around the body by the heart.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123blow",
    word: "blow",
    definition:
      "to move and make currents of air, or to make a sound by forcing air out of your mouth.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123body",
    word: "body",
    definition: "the whole physical structure that forms a person or animal.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123bread",
    word: "bread",
    definition: "a food made from flour, water and usually yeast, mixed together and baked.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123breath",
    word: "breath",
    definition: "the air that goes into and out of your lungs.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123brother",
    word: "brother",
    definition: "a man or boy with the same parents as another person.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123building",
    word: "building",
    definition: "a structure with walls and a roof, such as a house or a factory.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123burn",
    word: "burn",
    definition:
      "to be hurt, damaged or destroyed by fire or extreme heat, or to cause this to happen.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123business",
    word: "business",
    definition: "the activity of buying and selling goods and services.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123butter",
    word: "butter",
    definition:
      "a pale yellow food containing a lot of fat that is made from cream, usually spread on bread or used in cooking.",
    difficulty: "easy",
    eloRating: 800,
  },
  {
    _id: "123care",
    word: "care",
    definition: "the process of protecting someone or something, and providing what they need.",
    difficulty: "easy",
    eloRating: 800,
  },
];

export const hardDefinitions = [
  {
    _id: "5d99a788027a521eb8db0a89",
    word: "vilify",
    definition: "Spread negative information about",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0b1b",
    word: "gratuitous",
    definition: "Uncalled for; lacking good reason; unwarranted",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db09d7",
    word: "duress",
    definition: "Compulsory force or threat",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0b00",
    word: "limn",
    definition: "Make a portrait of",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0a42",
    word: "partisan",
    definition: "A fervent and even militant proponent of something",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db09ba",
    word: "contusion",
    definition: "An injury in which the skin is not broken",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0b1e",
    word: "incisive",
    definition: "Clear and sharp in analysis or expression",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0995",
    word: "aspersion",
    definition: "A disparaging remark",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0b16",
    word: "fabricate",
    definition: "To make up, invent",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db09d3",
    word: "divisive",
    definition: "Causing or characterized by disagreement or disunity",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0af8",
    word: "susurration",
    definition: "The indistinct sound of people whispering",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db09d2",
    word: "disrepute",
    definition: "The state of being held in low esteem",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0af2",
    word: "austere",
    definition: "Of a stern or strict bearing or demeanor",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db09a7",
    word: "circumlocution",
    definition: "An indirect way of expressing something",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0972",
    word: "abnegation",
    definition: "The denial and rejection of a doctrine or belief",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0a71",
    word: "solicitous",
    definition: "Full of anxiety and concern",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0b13",
    word: "enmity",
    definition: "Ill will; hatred; hostility",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0a7b",
    word: "toady",
    definition: "A person who tries to please someone to gain an advantage",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0a13",
    word: "injunction",
    definition: "A judicial remedy to prohibit a party from doing something",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0a03",
    word: "gratuitous",
    definition: "Unnecessary and unwarranted",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0ab3",
    word: "incendiary",
    definition:
      "Designed to set something on fire, tending to create public disturbances or violence",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0a4b",
    word: "philanthropic",
    definition: "Of or relating to charitable giving",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db09e5",
    word: "engender",
    definition: "Call forth",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0976",
    word: "accede",
    definition: "Yield to another's wish or opinion",
    difficulty: "hard",
    eloRating: 800,
  },
  {
    _id: "5d99a788027a521eb8db0ac2",
    word: "gauche",
    definition: "Lacking social polish",
    difficulty: "hard",
    eloRating: 800,
  },
];
