const rhymes = {
  novice: [
    {
      _id: "5e6ed68ad7af40377d04e2c1",
      word: "jack",
      rhymes: [
        { word: "back" },
        { word: "black" },
        { word: "track" },
        { word: "hack" },
        { word: "pack" },
        { word: "attack" },
        { word: "crack" },
        { word: "rack" },
        { word: "stack" },
        { word: "lack" },
        { word: "feedback" },
        { word: "tack" },
        { word: "plaque" },
        { word: "sack" },
        { word: "slack" },
        { word: "sac" },
        { word: "smack" },
        { word: "flak" },
        { word: "knack" },
        { word: "mac" },
        { word: "setback" },
        { word: "shack" },
        { word: "snack" },
        { word: "whack" },
        { word: "wrack" },
        { word: "lac" },
        { word: "aback" },
        { word: "tarmac" },
        { word: "yak" },
        { word: "piggyback" },
        { word: "drawback" },
        { word: "tac" },
        { word: "wack" },
        { word: "ransack" },
        { word: "maniac" },
        { word: "anorak" },
        { word: "almanac" },
        { word: "flack" },
        { word: "pac" },
        { word: "lilac" },
        { word: "zodiac" },
        { word: "hijack" },
        { word: "quack" },
        { word: "megalomaniac" },
        { word: "kickback" },
        { word: "throwback" },
        { word: "cognac" },
        { word: "cardiac" },
        { word: "paque" },
        { word: "ack" },
        { word: "kodak" },
        { word: "flashback" },
        { word: "backtrack" },
        { word: "backpack" },
        { word: "clack" },
        { word: "fallback" },
        { word: "fac" },
        { word: "comeback" },
        { word: "blackjack" },
        { word: "rucksack" },
        { word: "sidetrack" },
        { word: "outback" },
        { word: "cadillac" },
        { word: "nymphomaniac" },
        { word: "payback" },
        { word: "mack" },
        { word: "skipjack" },
        { word: "lumberjack" },
        { word: "flapjack" },
        { word: "knickknack" },
        { word: "wisecrack" },
        { word: "pak" },
        { word: "claque" },
        { word: "knapsack" },
        { word: "unpack" },
        { word: "counterattack" },
        { word: "quarterback" },
        { word: "rollback" },
        { word: "frack" },
        { word: "jacques" },
        { word: "dak" },
        { word: "greenback" },
        { word: "insomniac" },
        { word: "humpback" },
        { word: "razorback" },
        { word: "pontiac" },
        { word: "yack" },
        { word: "thwack" },
        { word: "cutback" },
        { word: "amnesiac" },
        { word: "eniac" },
        { word: "brack" },
        { word: "bushwhack" },
        { word: "hatchback" },
        { word: "plack" },
        { word: "soundtrack" },
        { word: "racetrack" },
        { word: "hunchback" },
        { word: "cac" },
        { word: "biofeedback" },
        { word: "bak" },
        { word: "smokestack" },
        { word: "nack" },
        { word: "crackerjack" },
        { word: "amtrack" },
        { word: "brac" },
        { word: "jac" },
        { word: "leatherback" },
        { word: "paperback" },
        { word: "kodiak" },
        { word: "paranoiac" },
        { word: "dac" },
        { word: "playback" },
        { word: "trac" },
        { word: "buyback" },
        { word: "haystack" },
        { word: "pullback" },
        { word: "gunnysack" },
        { word: "mak" },
        { word: "zack" },
        { word: "horseback" },
        { word: "thrack" },
        { word: "fullback" },
        { word: "hardback" },
        { word: "brownback" },
        { word: "sak" },
        { word: "repack" },
        { word: "trak" },
        { word: "tak" },
        { word: "halfback" },
        { word: "zak" },
        { word: "rak" },
        { word: "sacque" },
        { word: "sprack" },
        { word: "dack" },
        { word: "lak" },
        { word: "strack" },
        { word: "zach" },
        { word: "haque" },
        { word: "leaseback" },
        { word: "hackmatack" },
        { word: "merrimack" },
        { word: "wingback" },
        { word: "cornerback" },
        { word: "thack" },
        { word: "ryback" },
        { word: "prickleback" },
        { word: "wacke" },
        { word: "fishback" },
        { word: "chack" },
        { word: "spack" },
        { word: "spak" },
        { word: "hornback" },
        { word: "krack" },
      ],
      difficulty: "novice",
      eloRating: 1000,
    },
    {
      _id: "5e6ed68ad7af40377d04e2ff",
      word: "therefore",
      rhymes: [
        { word: "for" },
        { word: "war" },
        { word: "door" },
        { word: "store" },
        { word: "score" },
        { word: "more" },
        { word: "rapport" },
        { word: "core" },
        { word: "galore" },
        { word: "bore" },
        { word: "mentor" },
        { word: "floor" },
        { word: "sore" },
        { word: "drawer" },
        { word: "or" },
        { word: "before" },
        { word: "lore" },
        { word: "ore" },
        { word: "abhor" },
        { word: "explore" },
        { word: "soar" },
        { word: "anymore" },
        { word: "ignore" },
        { word: "implore" },
        { word: "corps" },
        { word: "restore" },
        { word: "nor" },
        { word: "whore" },
        { word: "furthermore" },
        { word: "shore" },
        { word: "pour" },
        { word: "dinosaur" },
        { word: "fore" },
        { word: "decor" },
        { word: "four" },
        { word: "adore" },
        { word: "gore" },
        { word: "chore" },
        { word: "your" },
        { word: "roar" },
        { word: "pore" },
        { word: "sophomore" },
        { word: "underscore" },
        { word: "deplore" },
        { word: "boar" },
        { word: "encore" },
        { word: "moore" },
        { word: "oar" },
        { word: "folklore" },
        { word: "therefor" },
        { word: "hoar" },
        { word: "heretofore" },
        { word: "offshore" },
        { word: "tor" },
        { word: "uproar" },
        { word: "yore" },
        { word: "guarantor" },
        { word: "hardcore" },
        { word: "outdoor" },
        { word: "cor" },
        { word: "stevedore" },
        { word: "carnivore" },
        { word: "sycamore" },
        { word: "troubadour" },
        { word: "tore" },
        { word: "wore" },
        { word: "thor" },
        { word: "evermore" },
        { word: "backdoor" },
        { word: "centaur" },
        { word: "snore" },
        { word: "spore" },
        { word: "commodore" },
        { word: "herbivore" },
        { word: "crore" },
        { word: "ashore" },
        { word: "salvador" },
        { word: "eyesore" },
        { word: "swore" },
        { word: "orr" },
        { word: "ecuador" },
        { word: "drugstore" },
        { word: "dore" },
        { word: "lor" },
        { word: "boer" },
        { word: "onshore" },
        { word: "mor" },
        { word: "flor" },
        { word: "labrador" },
        { word: "matador" },
        { word: "indoor" },
        { word: "seashore" },
        { word: "singapore" },
        { word: "bookstore" },
        { word: "torr" },
        { word: "senor" },
        { word: "smore" },
        { word: "albacore" },
        { word: "baltimore" },
        { word: "claymore" },
        { word: "igor" },
        { word: "inshore" },
        { word: "sor" },
        { word: "por" },
        { word: "timor" },
        { word: "phosphor" },
        { word: "postwar" },
        { word: "nevermore" },
        { word: "humidor" },
        { word: "bator" },
        { word: "chlor" },
        { word: "antiwar" },
        { word: "vore" },
        { word: "hors" },
        { word: "saur" },
        { word: "corr" },
        { word: "lahore" },
        { word: "frore" },
        { word: "dorr" },
        { word: "outpour" },
        { word: "prewar" },
        { word: "mohr" },
        { word: "ador" },
        { word: "scaur" },
        { word: "mhorr" },
        { word: "lakeshore" },
        { word: "outscore" },
        { word: "goar" },
        { word: "splore" },
        { word: "abor" },
        { word: "flore" },
        { word: "knorr" },
        { word: "longshore" },
        { word: "phore" },
        { word: "theodore" },
        { word: "blore" },
        { word: "glore" },
        { word: "ohr" },
        { word: "porr" },
        { word: "phthor" },
        { word: "shor" },
        { word: "isidore" },
        { word: "laure" },
        { word: "livor" },
        { word: "trovatore" },
        { word: "marcor" },
        { word: "horr" },
        { word: "lazor" },
        { word: "tenore" },
        { word: "laur" },
        { word: "glor" },
        { word: "ngor" },
        { word: "meritor" },
        { word: "ticor" },
      ],
      difficulty: "novice",
      eloRating: 1000,
    },
    {
      _id: "5e6b11582df5fb34a91ec2af",
      word: "later",
      rhymes: [
        { word: "coordinator" },
        { word: "mater" },
        { word: "cater" },
        { word: "curator" },
        { word: "operator" },
        { word: "perpetrator" },
        { word: "indicator" },
        { word: "generator" },
        { word: "accelerator" },
        { word: "administrator" },
        { word: "traitor" },
        { word: "crater" },
        { word: "equator" },
        { word: "elevator" },
        { word: "facilitator" },
        { word: "dictator" },
        { word: "denominator" },
        { word: "actuator" },
        { word: "mediator" },
        { word: "gaiter" },
        { word: "waiter" },
        { word: "refrigerator" },
        { word: "moderator" },
        { word: "alligator" },
        { word: "navigator" },
        { word: "creator" },
        { word: "agitator" },
        { word: "incubator" },
        { word: "greater" },
        { word: "instigator" },
        { word: "translator" },
        { word: "pater" },
        { word: "escalator" },
        { word: "accumulator" },
        { word: "manipulator" },
        { word: "calculator" },
        { word: "collaborator" },
        { word: "defibrillator" },
        { word: "regulator" },
        { word: "gladiator" },
        { word: "radiator" },
        { word: "amphitheater" },
        { word: "gator" },
        { word: "educator" },
        { word: "commentator" },
        { word: "fetor" },
        { word: "arbitrator" },
        { word: "aviator" },
        { word: "tater" },
        { word: "terminator" },
        { word: "stator" },
        { word: "skater" },
        { word: "innovator" },
        { word: "hater" },
        { word: "oscillator" },
        { word: "investigator" },
        { word: "carburetor" },
        { word: "activator" },
        { word: "percolator" },
        { word: "alternator" },
        { word: "baiter" },
        { word: "freighter" },
        { word: "insulator" },
        { word: "locator" },
        { word: "respirator" },
        { word: "simulator" },
        { word: "legislator" },
        { word: "ventilator" },
        { word: "communicator" },
        { word: "procrastinator" },
        { word: "amphitheatre" },
        { word: "incinerator" },
        { word: "originator" },
        { word: "excavator" },
        { word: "rater" },
        { word: "slater" },
        { word: "detonator" },
        { word: "eighter" },
        { word: "grater" },
        { word: "mercator" },
        { word: "animator" },
        { word: "illuminator" },
        { word: "imitator" },
        { word: "decorator" },
        { word: "stater" },
        { word: "illustrator" },
        { word: "liquidator" },
        { word: "estimator" },
        { word: "applicator" },
        { word: "speculator" },
        { word: "integrator" },
        { word: "infiltrator" },
        { word: "exterminator" },
        { word: "litigator" },
        { word: "negotiator" },
        { word: "demonstrator" },
        { word: "fabricator" },
        { word: "viator" },
        { word: "plater" },
        { word: "gater" },
        { word: "stimulator" },
        { word: "debater" },
        { word: "dater" },
        { word: "prater" },
        { word: "frater" },
        { word: "straighter" },
        { word: "vater" },
        { word: "vindicator" },
        { word: "bater" },
        { word: "violator" },
        { word: "modulator" },
        { word: "interrogator" },
        { word: "ater" },
        { word: "deflator" },
        { word: "inflator" },
        { word: "allocator" },
        { word: "evaporator" },
        { word: "conciliator" },
        { word: "syndicator" },
        { word: "consolidator" },
        { word: "penetrator" },
        { word: "renovator" },
        { word: "appropriator" },
        { word: "irrigator" },
        { word: "kater" },
        { word: "flater" },
        { word: "strater" },
      ],
      difficulty: "novice",
      eloRating: 1000,
    },
    {
      _id: "5e6f0868f12f4e3abf6c8913",
      word: "thread",
      rhymes: [
        { word: "read" },
        { word: "lead" },
        { word: "head" },
        { word: "red" },
        { word: "bed" },
        { word: "spread" },
        { word: "shed" },
        { word: "tread" },
        { word: "led" },
        { word: "bread" },
        { word: "dead" },
        { word: "ahead" },
        { word: "dread" },
        { word: "embed" },
        { word: "overhead" },
        { word: "pled" },
        { word: "watershed" },
        { word: "said" },
        { word: "wed" },
        { word: "instead" },
        { word: "ed" },
        { word: "stead" },
        { word: "shred" },
        { word: "widespread" },
        { word: "shead" },
        { word: "bulkhead" },
        { word: "med" },
        { word: "aforesaid" },
        { word: "sled" },
        { word: "fed" },
        { word: "ted" },
        { word: "homestead" },
        { word: "spearhead" },
        { word: "misread" },
        { word: "retread" },
        { word: "ged" },
        { word: "infrared" },
        { word: "bled" },
        { word: "coed" },
        { word: "egghead" },
        { word: "imbed" },
        { word: "abed" },
        { word: "misled" },
        { word: "bred" },
        { word: "fred" },
        { word: "sped" },
        { word: "inbred" },
        { word: "zed" },
        { word: "figurehead" },
        { word: "thoroughbred" },
        { word: "hotbed" },
        { word: "deadhead" },
        { word: "blockhead" },
        { word: "beachhead" },
        { word: "ned" },
        { word: "masthead" },
        { word: "warhead" },
        { word: "airhead" },
        { word: "letterhead" },
        { word: "bobsled" },
        { word: "behead" },
        { word: "loggerhead" },
        { word: "fled" },
        { word: "redhead" },
        { word: "bedspread" },
        { word: "godhead" },
        { word: "whitehead" },
        { word: "arrowhead" },
        { word: "gingerbread" },
        { word: "bridgehead" },
        { word: "copperhead" },
        { word: "bloodshed" },
        { word: "bullhead" },
        { word: "riverbed" },
        { word: "seabed" },
        { word: "dred" },
        { word: "redd" },
        { word: "deathbed" },
        { word: "flathead" },
        { word: "skinhead" },
        { word: "woodshed" },
        { word: "newlywed" },
        { word: "wellhead" },
        { word: "purebred" },
        { word: "flatbed" },
        { word: "featherbed" },
        { word: "farmstead" },
        { word: "shithead" },
        { word: "unwed" },
        { word: "swed" },
        { word: "roundhead" },
        { word: "freda" },
        { word: "trailhead" },
        { word: "cornbread" },
        { word: "drumhead" },
        { word: "steelhead" },
        { word: "unread" },
        { word: "unsaid" },
        { word: "hardhead" },
        { word: "armstead" },
        { word: "waterbed" },
        { word: "sayed" },
        { word: "thickhead" },
        { word: "dragonhead" },
        { word: "broadhead" },
        { word: "overfed" },
        { word: "jed" },
        { word: "interbred" },
        { word: "horsehead" },
        { word: "marblehead" },
        { word: "riverhead" },
        { word: "weatherhead" },
        { word: "nedd" },
        { word: "anstead" },
        { word: "fread" },
        { word: "unted" },
      ],
      difficulty: "novice",
      eloRating: 1000,
    },
  ],
  journeyman: [
    {
      _id: "5e6f0868f12f4e3abf6c8914",
      word: "throat",
      rhymes: [
        { word: "note" },
        { word: "boat" },
        { word: "coat" },
        { word: "promote" },
        { word: "anecdote" },
        { word: "float" },
        { word: "quote" },
        { word: "denote" },
        { word: "goat" },
        { word: "remote" },
        { word: "rote" },
        { word: "vote" },
        { word: "antidote" },
        { word: "gloat" },
        { word: "tote" },
        { word: "mote" },
        { word: "wrote" },
        { word: "haute" },
        { word: "devote" },
        { word: "dote" },
        { word: "moat" },
        { word: "cote" },
        { word: "connote" },
        { word: "scapegoat" },
        { word: "afloat" },
        { word: "keynote" },
        { word: "smote" },
        { word: "bloat" },
        { word: "oat" },
        { word: "asymptote" },
        { word: "choate" },
        { word: "stoat" },
        { word: "footnote" },
        { word: "groat" },
        { word: "demote" },
        { word: "creosote" },
        { word: "petticoat" },
        { word: "shoat" },
        { word: "cutthroat" },
        { word: "turncoat" },
        { word: "roat" },
        { word: "showboat" },
        { word: "overcoat" },
        { word: "capote" },
        { word: "raincoat" },
        { word: "hote" },
        { word: "tugboat" },
        { word: "sailboat" },
        { word: "redcoat" },
        { word: "banknote" },
        { word: "rowboat" },
        { word: "blote" },
        { word: "lifeboat" },
        { word: "shote" },
        { word: "motorboat" },
        { word: "steamboat" },
        { word: "grote" },
        { word: "undercoat" },
        { word: "unquote" },
        { word: "gunboat" },
        { word: "speedboat" },
        { word: "sloat" },
        { word: "clote" },
        { word: "houseboat" },
        { word: "troat" },
        { word: "riverboat" },
        { word: "flote" },
        { word: "towboat" },
        { word: "pote" },
        { word: "powerboat" },
        { word: "ferryboat" },
        { word: "outvote" },
        { word: "misquote" },
        { word: "underwrote" },
        { word: "flatboat" },
        { word: "vogt" },
        { word: "sproat" },
        { word: "rewrote" },
        { word: "overwrote" },
        { word: "uncoat" },
      ],
      difficulty: "journeyman",
      eloRating: 1400,
    },
    {
      _id: "5e6f0ba81530d53b62a85e87",
      word: "mistake",
      rhymes: [
        { word: "awake" },
        { word: "break" },
        { word: "take" },
        { word: "cake" },
        { word: "make" },
        { word: "forsake" },
        { word: "snake" },
        { word: "wake" },
        { word: "stake" },
        { word: "shake" },
        { word: "opaque" },
        { word: "rake" },
        { word: "partake" },
        { word: "undertake" },
        { word: "lake" },
        { word: "brake" },
        { word: "sake" },
        { word: "steak" },
        { word: "fake" },
        { word: "ache" },
        { word: "flake" },
        { word: "overtake" },
        { word: "earthquake" },
        { word: "intake" },
        { word: "pancake" },
        { word: "bake" },
        { word: "namesake" },
        { word: "uptake" },
        { word: "drake" },
        { word: "betake" },
        { word: "headache" },
        { word: "snowflake" },
        { word: "jake" },
        { word: "slake" },
        { word: "retake" },
        { word: "quake" },
        { word: "outbreak" },
        { word: "hake" },
        { word: "rattlesnake" },
        { word: "caique" },
        { word: "remake" },
        { word: "keepsake" },
        { word: "mandrake" },
        { word: "blake" },
        { word: "strake" },
        { word: "crake" },
        { word: "handshake" },
        { word: "heartache" },
        { word: "daybreak" },
        { word: "heartbreak" },
        { word: "cupcake" },
        { word: "ake" },
        { word: "bellyache" },
        { word: "cheesecake" },
        { word: "milkshake" },
        { word: "spake" },
        { word: "sweepstake" },
        { word: "outtake" },
        { word: "fruitcake" },
        { word: "shortcake" },
        { word: "backache" },
        { word: "pake" },
        { word: "beefsteak" },
        { word: "kittiwake" },
        { word: "haik" },
        { word: "muckrake" },
        { word: "shaykh" },
        { word: "paik" },
        { word: "claik" },
        { word: "naik" },
        { word: "hotcake" },
        { word: "dake" },
        { word: "shaikh" },
        { word: "clake" },
        { word: "straik" },
        { word: "haick" },
        { word: "shoemake" },
        { word: "plake" },
        { word: "interlake" },
      ],
      difficulty: "journeyman",
      eloRating: 1400,
    },
    {
      _id: "5e6ed68ad7af40377d04e372",
      word: "support",
      rhymes: [
        { word: "court" },
        { word: "short" },
        { word: "report" },
        { word: "port" },
        { word: "sport" },
        { word: "thwart" },
        { word: "resort" },
        { word: "transport" },
        { word: "purport" },
        { word: "forte" },
        { word: "exhort" },
        { word: "tort" },
        { word: "import" },
        { word: "retort" },
        { word: "consort" },
        { word: "sort" },
        { word: "comport" },
        { word: "escort" },
        { word: "cavort" },
        { word: "distort" },
        { word: "snort" },
        { word: "airport" },
        { word: "extort" },
        { word: "wart" },
        { word: "torte" },
        { word: "fort" },
        { word: "ort" },
        { word: "abort" },
        { word: "passport" },
        { word: "ct" },
        { word: "deport" },
        { word: "mort" },
        { word: "davenport" },
        { word: "quart" },
        { word: "athwart" },
        { word: "carport" },
        { word: "teleport" },
        { word: "stuart" },
        { word: "contort" },
        { word: "bort" },
        { word: "assort" },
        { word: "seaport" },
        { word: "swart" },
        { word: "cort" },
        { word: "porte" },
        { word: "boart" },
        { word: "quarte" },
        { word: "dort" },
        { word: "freeport" },
        { word: "underreport" },
        { word: "spaceport" },
        { word: "shreveport" },
        { word: "bridgeport" },
        { word: "misreport" },
        { word: "foret" },
        { word: "reexport" },
        { word: "lockport" },
      ],
      difficulty: "journeyman",
      eloRating: 1400,
    },
    {
      _id: "5e6b163aefc7093554adb111",
      word: "control",
      rhymes: [
        { word: "roll" },
        { word: "hole" },
        { word: "troll" },
        { word: "pole" },
        { word: "console" },
        { word: "soul" },
        { word: "bowl" },
        { word: "goal" },
        { word: "sole" },
        { word: "mole" },
        { word: "role" },
        { word: "whole" },
        { word: "poll" },
        { word: "toll" },
        { word: "droll" },
        { word: "cajole" },
        { word: "coal" },
        { word: "extol" },
        { word: "dole" },
        { word: "shoal" },
        { word: "stroll" },
        { word: "enroll" },
        { word: "oriole" },
        { word: "parole" },
        { word: "ole" },
        { word: "atoll" },
        { word: "cole" },
        { word: "scroll" },
        { word: "loophole" },
        { word: "patrol" },
        { word: "stole" },
        { word: "bole" },
        { word: "charcoal" },
        { word: "payroll" },
        { word: "pigeonhole" },
        { word: "foal" },
        { word: "knoll" },
        { word: "thole" },
        { word: "pothole" },
        { word: "dhole" },
        { word: "kohl" },
        { word: "casserole" },
        { word: "tole" },
        { word: "manhole" },
        { word: "dipole" },
        { word: "sinkhole" },
        { word: "boll" },
        { word: "skoal" },
        { word: "tadpole" },
        { word: "buttonhole" },
        { word: "bankroll" },
        { word: "seoul" },
        { word: "stol" },
        { word: "seminole" },
        { word: "blowhole" },
        { word: "redpoll" },
        { word: "pinhole" },
        { word: "nicole" },
        { word: "viole" },
        { word: "keyhole" },
        { word: "foxhole" },
        { word: "cubbyhole" },
        { word: "amphibole" },
        { word: "noll" },
        { word: "flagpole" },
        { word: "espanol" },
        { word: "glycol" },
        { word: "interpol" },
        { word: "shole" },
        { word: "monopole" },
        { word: "fishbowl" },
        { word: "ecole" },
        { word: "pistole" },
        { word: "ghole" },
        { word: "glycerol" },
        { word: "kol" },
        { word: "rolle" },
        { word: "rol" },
        { word: "nole" },
        { word: "posthole" },
        { word: "lodgepole" },
        { word: "croll" },
        { word: "mousehole" },
        { word: "groll" },
        { word: "snowl" },
        { word: "ohl" },
        { word: "colle" },
        { word: "decontrol" },
        { word: "sowle" },
        { word: "hoel" },
        { word: "anatole" },
        { word: "agricole" },
        { word: "devaul" },
      ],
      difficulty: "journeyman",
      eloRating: 1400,
    },
    {
      _id: "5e6f0868f12f4e3abf6c8933",
      word: "complex",
      rhymes: [
        { word: "sex" },
        { word: "vex" },
        { word: "flex" },
        { word: "x" },
        { word: "apex" },
        { word: "ex" },
        { word: "annex" },
        { word: "next" },
        { word: "rex" },
        { word: "effects" },
        { word: "vertex" },
        { word: "dex" },
        { word: "perplex" },
        { word: "hex" },
        { word: "lex" },
        { word: "duplex" },
        { word: "tex" },
        { word: "convex" },
        { word: "plex" },
        { word: "multiplex" },
        { word: "latex" },
        { word: "simplex" },
        { word: "telex" },
        { word: "mex" },
        { word: "specs" },
        { word: "amex" },
        { word: "objects" },
        { word: "triplex" },
        { word: "unisex" },
        { word: "decks" },
        { word: "nex" },
        { word: "aix" },
        { word: "respects" },
        { word: "checks" },
        { word: "subjects" },
        { word: "projects" },
        { word: "specks" },
        { word: "flecks" },
        { word: "reflects" },
        { word: "sphex" },
        { word: "videotex" },
        { word: "suspects" },
        { word: "cheques" },
        { word: "treks" },
        { word: "bottlenecks" },
        { word: "dissects" },
        { word: "eques" },
        { word: "wrecks" },
        { word: "aztecs" },
        { word: "execs" },
        { word: "necks" },
        { word: "kecks" },
        { word: "rejects" },
        { word: "ejects" },
        { word: "expects" },
        { word: "techs" },
        { word: "czechs" },
        { word: "pecks" },
        { word: "intellects" },
        { word: "intersects" },
        { word: "roughnecks" },
        { word: "paychecks" },
        { word: "fecks" },
        { word: "whelks" },
        { word: "becks" },
        { word: "rednecks" },
        { word: "discotheques" },
        { word: "tenrecs" },
        { word: "turtlenecks" },
        { word: "biotechs" },
        { word: "entex" },
      ],
      difficulty: "journeyman",
      eloRating: 1400,
    },
    {
      _id: "5e6b14c5745bc434fa0f7aef",
      word: "sometime",
      rhymes: [
        { word: "time" },
        { word: "paradigm" },
        { word: "sublime" },
        { word: "rhyme" },
        { word: "prime" },
        { word: "crime" },
        { word: "lime" },
        { word: "anytime" },
        { word: "chime" },
        { word: "meantime" },
        { word: "dime" },
        { word: "maritime" },
        { word: "nighttime" },
        { word: "climb" },
        { word: "enzyme" },
        { word: "pantomime" },
        { word: "downtime" },
        { word: "longtime" },
        { word: "mime" },
        { word: "pastime" },
        { word: "slime" },
        { word: "lifetime" },
        { word: "thyme" },
        { word: "grime" },
        { word: "overtime" },
        { word: "clime" },
        { word: "lunchtime" },
        { word: "stime" },
        { word: "onetime" },
        { word: "wintertime" },
        { word: "summertime" },
        { word: "daytime" },
        { word: "ragtime" },
        { word: "chyme" },
        { word: "hime" },
        { word: "airtime" },
        { word: "halftime" },
        { word: "bedtime" },
        { word: "dinnertime" },
        { word: "springtime" },
        { word: "anaheim" },
        { word: "centime" },
        { word: "sime" },
        { word: "mealtime" },
        { word: "heim" },
        { word: "wartime" },
        { word: "blenheim" },
        { word: "noontime" },
        { word: "schooltime" },
        { word: "peacetime" },
        { word: "kime" },
        { word: "fulltime" },
        { word: "alltime" },
      ],
      difficulty: "journeyman",
      eloRating: 1400,
    },
  ],
  expert: [
    {
      _id: "5e6f0ba81530d53b62a85e80",
      word: "judge",
      rhymes: [
        { word: "nudge" },
        { word: "grudge" },
        { word: "fudge" },
        { word: "drudge" },
        { word: "trudge" },
        { word: "budge" },
        { word: "sludge" },
        { word: "smudge" },
        { word: "begrudge" },
        { word: "adjudge" },
        { word: "kludge" },
        { word: "bludge" },
        { word: "prejudge" },
        { word: "pudge" },
        { word: "rudge" },
        { word: "mudge" },
        { word: "snudge" },
        { word: "misjudge" },
      ],
      difficulty: "expert",
      eloRating: 1800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c88f2",
      word: "pool",
      rhymes: [
        { word: "school" },
        { word: "rule" },
        { word: "cool" },
        { word: "tool" },
        { word: "fuel" },
        { word: "fool" },
        { word: "stool" },
        { word: "cruel" },
        { word: "dual" },
        { word: "ridicule" },
        { word: "mule" },
        { word: "vestibule" },
        { word: "jewel" },
        { word: "drool" },
        { word: "tulle" },
        { word: "minuscule" },
        { word: "molecule" },
        { word: "spool" },
        { word: "yule" },
        { word: "ghoul" },
        { word: "joule" },
        { word: "cesspool" },
        { word: "whirlpool" },
        { word: "carpool" },
        { word: "preschool" },
        { word: "overrule" },
        { word: "istanbul" },
        { word: "boule" },
        { word: "thule" },
        { word: "raul" },
        { word: "retool" },
        { word: "liverpool" },
        { word: "highschool" },
        { word: "kool" },
        { word: "uncool" },
        { word: "brule" },
        { word: "tuille" },
        { word: "buhl" },
        { word: "dule" },
        { word: "supercool" },
        { word: "misrule" },
        { word: "tuel" },
        { word: "jule" },
        { word: "saccule" },
        { word: "boulle" },
        { word: "ruel" },
        { word: "rahul" },
      ],
      difficulty: "expert",
      eloRating: 1800,
    },
    {
      _id: "5e6ed68ad7af40377d04e36d",
      word: "source",
      rhymes: [
        { word: "force" },
        { word: "course" },
        { word: "horse" },
        { word: "endorse" },
        { word: "coarse" },
        { word: "remorse" },
        { word: "reinforce" },
        { word: "enforce" },
        { word: "intercourse" },
        { word: "workforce" },
        { word: "concourse" },
        { word: "divorce" },
        { word: "perforce" },
        { word: "hoarse" },
        { word: "norse" },
        { word: "bourse" },
        { word: "gorse" },
        { word: "morse" },
        { word: "torse" },
        { word: "corse" },
        { word: "workhorse" },
        { word: "scorce" },
        { word: "dorse" },
        { word: "clotheshorse" },
        { word: "torsk" },
        { word: "gorce" },
        { word: "forse" },
        { word: "racehorse" },
        { word: "scorse" },
        { word: "counterforce" },
        { word: "midcourse" },
        { word: "fourths" },
        { word: "vorce" },
      ],
      difficulty: "expert",
      eloRating: 1800,
    },
    {
      _id: "5e6b11582df5fb34a91ec26d",
      word: "better",
      rhymes: [
        { word: "letter" },
        { word: "fetter" },
        { word: "setter" },
        { word: "debtor" },
        { word: "sweater" },
        { word: "newsletter" },
        { word: "netter" },
        { word: "getter" },
        { word: "wetter" },
        { word: "fretter" },
        { word: "bettor" },
        { word: "pacesetter" },
        { word: "whetter" },
        { word: "petter" },
        { word: "petar" },
        { word: "jetter" },
        { word: "petre" },
        { word: "petr" },
        { word: "etter" },
        { word: "yetter" },
        { word: "ketter" },
        { word: "retter" },
        { word: "geter" },
      ],
      difficulty: "expert",
      eloRating: 1800,
    },
  ],
  master: [
    {
      _id: "5e6f0ba81530d53b62a85e70",
      word: "eventually",
      rhymes: [
        { word: "essentially" },
        { word: "exponentially" },
        { word: "potentially" },
        { word: "preferentially" },
        { word: "confidentially" },
        { word: "sensually" },
        { word: "presidentially" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0ba81530d53b62a85e5c",
      word: "announced",
      rhymes: [
        { word: "pronounced" },
        { word: "denounced" },
        { word: "renounced" },
        { word: "bounced" },
        { word: "pounced" },
        { word: "flounced" },
        { word: "unannounced" },
        { word: "trounced" },
        { word: "jounced" },
        { word: "mispronounced" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c890b",
      word: "standard",
      rhymes: [
        { word: "substandard" },
        { word: "nonstandard" },
        { word: "slandered" },
        { word: "pandered" },
        { word: "meandered" },
        { word: "gerrymandered" },
        { word: "glandered" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0ba81530d53b62a85eeb",
      word: "hunter",
      rhymes: [
        { word: "punter" },
        { word: "hinter" },
        { word: "sinter" },
        { word: "bunter" },
        { word: "headhunter" },
        { word: "blunter" },
        { word: "linter" },
        { word: "tinter" },
        { word: "shunter" },
        { word: "stinter" },
        { word: "grunter" },
        { word: "gunter" },
        { word: "squinter" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6b14c5745bc434fa0f7ae0",
      word: "remember",
      rhymes: [
        { word: "member" },
        { word: "ember" },
        { word: "september" },
        { word: "december" },
        { word: "november" },
        { word: "dismember" },
        { word: "misremember" },
        { word: "nonmember" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6b14c5745bc434fa0f7b11",
      word: "beginning",
      rhymes: [
        { word: "underpinning" },
        { word: "printing" },
        { word: "winning" },
        { word: "spinning" },
        { word: "imprinting" },
        { word: "grinning" },
        { word: "pinning" },
        { word: "ginning" },
        { word: "binning" },
        { word: "dinning" },
        { word: "finning" },
        { word: "thinning" },
        { word: "sinning" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c88c3",
      word: "discovery",
      rhymes: [
        { word: "recovery" },
        { word: "shivery" },
        { word: "quivery" },
        { word: "rivery" },
        { word: "rediscovery" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0ba81530d53b62a85e1b",
      word: "mirror",
      rhymes: [
        { word: "dearer" },
        { word: "clearer" },
        { word: "shearer" },
        { word: "nearer" },
        { word: "queerer" },
        { word: "severer" },
        { word: "sherer" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c8892",
      word: "swimming",
      rhymes: [
        { word: "skimming" },
        { word: "trimming" },
        { word: "brimming" },
        { word: "dimming" },
        { word: "slimming" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c88b5",
      word: "choice",
      rhymes: [
        { word: "voice" },
        { word: "rejoice" },
        { word: "joyce" },
        { word: "boyce" },
        { word: "alois" },
        { word: "joice" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0ba81530d53b62a85e12",
      word: "improve",
      rhymes: [
        { word: "move" },
        { word: "groove" },
        { word: "prove" },
        { word: "disprove" },
        { word: "approve" },
        { word: "remove" },
        { word: "behoove" },
        { word: "disapprove" },
        { word: "hoove" },
        { word: "poove" },
        { word: "countermove" },
        { word: "veuve" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0ba81530d53b62a85efe",
      word: "ourselves",
      rhymes: [
        { word: "themselves" },
        { word: "elves" },
        { word: "shelves" },
        { word: "pelves" },
        { word: "selves" },
        { word: "yourselves" },
        { word: "theirselves" },
        { word: "bookshelves" },
        { word: "delves" },
        { word: "twelves" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6b163aefc7093554adb0b9",
      word: "north",
      rhymes: [
        { word: "forth" },
        { word: "swarth" },
        { word: "henceforth" },
        { word: "fourth" },
        { word: "orth" },
        { word: "thenceforth" },
        { word: "warth" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c88b9",
      word: "college",
      rhymes: [
        { word: "knowledge" },
        { word: "acknowledge" },
        { word: "tallage" },
        { word: "smallage" },
        { word: "hallage" },
        { word: "stallage" },
        { word: "haulage" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c8849",
      word: "factory",
      rhymes: [
        { word: "refractory" },
        { word: "satisfactory" },
        { word: "olfactory" },
        { word: "unsatisfactory" },
        { word: "tractory" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c885f",
      word: "local",
      rhymes: [
        { word: "vocal" },
        { word: "focal" },
        { word: "socle" },
        { word: "bocal" },
        { word: "phocal" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0ba81530d53b62a85e3d",
      word: "stronger",
      rhymes: [
        { word: "longer" },
        { word: "conger" },
        { word: "fishmonger" },
        { word: "warmonger" },
        { word: "wronger" },
        { word: "songer" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6b0f3b9df1573227318f63",
      word: "give",
      rhymes: [
        { word: "live" },
        { word: "forgive" },
        { word: "sieve" },
        { word: "combative" },
        { word: "liv" },
        { word: "relive" },
        { word: "outlive" },
        { word: "determinative" },
        { word: "corroborative" },
        { word: "misgive" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c8871",
      word: "pocket",
      rhymes: [
        { word: "rocket" },
        { word: "docket" },
        { word: "socket" },
        { word: "toquet" },
        { word: "sprocket" },
        { word: "pickpocket" },
        { word: "skyrocket" },
        { word: "locket" },
        { word: "docquet" },
        { word: "roquet" },
        { word: "brocket" },
        { word: "crocket" },
        { word: "hocket" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6f0868f12f4e3abf6c88bf",
      word: "creature",
      rhymes: [
        { word: "feature" },
        { word: "teacher" },
        { word: "preacher" },
        { word: "leacher" },
        { word: "bleacher" },
        { word: "reacher" },
        { word: "schoolteacher" },
        { word: "beecher" },
        { word: "screecher" },
        { word: "beacher" },
        { word: "peacher" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
    {
      _id: "5e6b14c5745bc434fa0f7b23",
      word: "common",
      rhymes: [
        { word: "brahmin" },
        { word: "aman" },
        { word: "uncommon" },
        { word: "lawman" },
        { word: "raman" },
        { word: "swagman" },
        { word: "rahman" },
        { word: "naaman" },
        { word: "palmin" },
        { word: "jomon" },
        { word: "romine" },
      ],
      difficulty: "master",
      eloRating: 2800,
    },
  ],
};

export default rhymes;
